package br.org.rosalina.social.student;
import br.org.rosalina.social.audit.AuditService; import br.org.rosalina.social.catalog.*; import br.org.rosalina.social.common.*; import java.util.*; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class StudentService {
 private final StudentRepository students; private final CatalogItemRepository catalogs; private final AuditService audit; public StudentService(StudentRepository s,CatalogItemRepository c,AuditService a){students=s;catalogs=c;audit=a;}
 public Student create(StudentController.Request r){validate(r,null);Student s=new Student();apply(s,r);students.save(s);audit.record("CREATE","STUDENT",s.getId());return s;}
 public Student update(UUID id,StudentController.Request r){Student s=students.findWithDetailsById(id).orElseThrow(()->new NotFoundException("Aluno não encontrado."));validate(r,id);apply(s,r);students.save(s);audit.record("UPDATE","STUDENT",id);return s;}
 public Student get(UUID id){return students.findWithDetailsById(id).orElseThrow(()->new NotFoundException("Aluno não encontrado."));}
 @Transactional(readOnly=true) public Page<Student> list(String name,String cpf,StudentStatus status,Pageable page){return students.search(blank(name),digits(cpf),status,page);}
 public Student setStatus(UUID id,StudentStatus status){Student s=students.findById(id).orElseThrow(()->new NotFoundException("Aluno não encontrado."));s.setStatus(status);students.save(s);audit.record(status==StudentStatus.ATIVO?"ACTIVATE":"DEACTIVATE","STUDENT",id);return s;}
 private void validate(StudentController.Request r,UUID existing){String cpf=digits(r.cpf());if(cpf!=null&&!DocumentValidator.cpf(cpf))throw new ApiException(HttpStatus.BAD_REQUEST,"CPF inválido."); if(r.relatives()!=null){for(var relative:r.relatives()){String relativeCpf=digits(relative.cpf());if(relativeCpf!=null&&!DocumentValidator.cpf(relativeCpf))throw new ApiException(HttpStatus.BAD_REQUEST,"CPF do familiar inválido.");}}if(cpf!=null&&students.existsByCpf(cpf)&&(existing==null||!cpf.equals(students.findById(existing).map(Student::getCpf).orElse(null))))throw new ApiException(HttpStatus.CONFLICT,"CPF já cadastrado.");if(r.birthDate().isAfter(java.time.LocalDate.now())||(r.startDate()!=null&&r.startDate().isAfter(java.time.LocalDate.now())))throw new ApiException(HttpStatus.BAD_REQUEST,"Datas não podem estar no futuro.");if(r.relatives()==null||r.relatives().stream().noneMatch(x->x.type()==RelativeType.RESPONSAVEL&&x.name()!=null&&!x.name().isBlank()))throw new ApiException(HttpStatus.BAD_REQUEST,"Nome do responsável é obrigatório.");if(r.relatives().stream().map(StudentController.RelativeRequest::type).distinct().count()!=r.relatives().size())throw new ApiException(HttpStatus.BAD_REQUEST,"Cada tipo de familiar pode ser informado uma vez.");if(r.zipCode()!=null&&!r.zipCode().replaceAll("\\D","").matches("\\d{8}"))throw new ApiException(HttpStatus.BAD_REQUEST,"CEP deve conter 8 dígitos.");}
 private void apply(Student s,StudentController.Request r){s.setStatus(r.status());s.setName(r.name().trim());s.setActivity(active(r.activityId(),CatalogCategory.ATIVIDADE));s.setBirthDate(r.birthDate());s.setRg(blank(r.rg()));s.setCpf(digits(r.cpf()));s.setCadunico(r.cadunico());s.setNis(digits(r.nis()));s.setNationalHealthCard(digits(r.nationalHealthCard()));s.setAddress(blank(r.address()));s.setNeighborhood(blank(r.neighborhood()));s.setReferencePoint(blank(r.referencePoint()));s.setCity(blank(r.city()));s.setZipCode(digits(r.zipCode()));s.setStartDate(r.startDate());s.setGuardianPhone(digits(r.guardianPhone()));s.setGuardianEmail(blank(r.guardianEmail()));s.setStudentPhone(digits(r.studentPhone()));s.setStudentEmail(blank(r.studentEmail()));s.setParentsRelationshipStatus(r.parentsRelationshipStatus());
 List<StudentRelative> relatives=new ArrayList<>();if(r.relatives()!=null)for(var x:r.relatives()){StudentRelative p=new StudentRelative();p.setType(x.type());p.setKinship(blank(x.kinship()));p.setName(x.name().trim());p.setBirthDate(x.birthDate());p.setOccupation(optional(x.occupationId(),CatalogCategory.OCUPACAO));p.setLiterate(x.literate());p.setEducation(optional(x.educationId(),CatalogCategory.ESCOLARIDADE));p.setPhone(digits(x.phone()));p.setRg(blank(x.rg()));p.setCpf(digits(x.cpf()));p.setVoterRegistration(blank(x.voterRegistration()));relatives.add(p);}s.replaceRelatives(relatives); if(r.socioeconomic()!=null){SocioeconomicProfile p=new SocioeconomicProfile();var x=r.socioeconomic();p.setHousingType(optional(x.housingTypeId(),CatalogCategory.TIPO_MORADIA));p.setAcquisitionType(optional(x.acquisitionTypeId(),CatalogCategory.FORMA_AQUISICAO));p.setWallType(optional(x.wallTypeId(),CatalogCategory.TIPO_VEDACAO));p.setFloorType(optional(x.floorTypeId(),CatalogCategory.TIPO_PISO));p.setHasElectricity(x.hasElectricity());p.setWaterSupply(optional(x.waterSupplyId(),CatalogCategory.AGUA));p.setSewage(optional(x.sewageId(),CatalogCategory.ESGOTO));p.setGarbageCollection(optional(x.garbageCollectionId(),CatalogCategory.COLETA_LIXO));p.setWaterExpense(x.waterExpense());p.setElectricityExpense(x.electricityExpense());p.setPhoneExpense(x.phoneExpense());p.setRentOrFinancingExpense(x.rentOrFinancingExpense());p.setFoodExpense(x.foodExpense());p.setHouseholdIncome(x.householdIncome());p.setHasOtherAssets(x.hasOtherAssets());p.setHasOtherProperty(x.hasOtherProperty());p.setHasVehicle(x.hasVehicle());p.setReceivesBolsaFamilia(x.receivesBolsaFamilia());p.setReceivesBpc(x.receivesBpc());p.setReceivesRetirement(x.receivesRetirement());s.setSocioeconomicProfile(p);}else s.setSocioeconomicProfile(null); }
 private CatalogItem active(UUID id,CatalogCategory category){CatalogItem item=catalogs.findById(id).orElseThrow(()->new NotFoundException("Catálogo não encontrado."));if(!item.isActive()||item.getCategory()!=category)throw new ApiException(HttpStatus.BAD_REQUEST,"Opção de catálogo inválida ou inativa.");return item;} private CatalogItem optional(UUID id,CatalogCategory category){return id==null?null:active(id,category);} private static String blank(String s){return s==null||s.isBlank()?null:s.trim();} private static String digits(String s){return s==null||s.isBlank()?null:s.replaceAll("\\D","");}
}
