package br.org.rosalina.social.student;
import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.math.BigDecimal; import java.time.LocalDate; import java.util.*; import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/students") public class StudentController {
 private final StudentService service; public StudentController(StudentService s){service=s;}
 public record RelativeRequest(@NotNull RelativeType type,String kinship,@NotBlank @Size(max=150) String name,@Past LocalDate birthDate,UUID occupationId,Boolean literate,UUID educationId,@Pattern(regexp="^$|^[0-9() +\\-]{7,20}$",message="Telefone inválido") String phone,String rg,String cpf,String voterRegistration){}
 public record SocioeconomicRequest(UUID housingTypeId,UUID acquisitionTypeId,UUID wallTypeId,UUID floorTypeId,Boolean hasElectricity,UUID waterSupplyId,UUID sewageId,UUID garbageCollectionId,@DecimalMin(value="0.00") BigDecimal waterExpense,@DecimalMin(value="0.00") BigDecimal electricityExpense,@DecimalMin(value="0.00") BigDecimal phoneExpense,@DecimalMin(value="0.00") BigDecimal rentOrFinancingExpense,@DecimalMin(value="0.00") BigDecimal foodExpense,@DecimalMin(value="0.00") BigDecimal householdIncome,Boolean hasOtherAssets,Boolean hasOtherProperty,Boolean hasVehicle,Boolean receivesBolsaFamilia,Boolean receivesBpc,Boolean receivesRetirement){}
 public record Request(@NotNull StudentStatus status,@NotBlank @Size(max=150) String name,@NotNull UUID activityId,@NotNull @Past LocalDate birthDate,String rg,String cpf,Boolean cadunico,String nis,String nationalHealthCard,String address,String neighborhood,String referencePoint,String city,@Pattern(regexp="^[0-9\\-]{0,9}$",message="CEP inválido") String zipCode,@PastOrPresent LocalDate startDate,@NotBlank @Pattern(regexp="^[0-9() +\\-]{7,20}$",message="Telefone inválido") String guardianPhone,@Email String guardianEmail,@Pattern(regexp="^$|^[0-9() +\\-]{7,20}$",message="Telefone inválido") String studentPhone,@Email String studentEmail,ParentsRelationshipStatus parentsRelationshipStatus,@NotNull @Valid List<RelativeRequest> relatives,@Valid SocioeconomicRequest socioeconomic){}
 public record StatusRequest(@NotNull StudentStatus status){} public record CatalogRef(UUID id,String name){} public record RelativeResponse(RelativeType type,String kinship,String name,LocalDate birthDate,CatalogRef occupation,Boolean literate,CatalogRef education,String phone,String rg,String cpf,String voterRegistration){} public record SocioeconomicResponse(CatalogRef housingType,CatalogRef acquisitionType,CatalogRef wallType,CatalogRef floorType,Boolean hasElectricity,CatalogRef waterSupply,CatalogRef sewage,CatalogRef garbageCollection,BigDecimal waterExpense,BigDecimal electricityExpense,BigDecimal phoneExpense,BigDecimal rentOrFinancingExpense,BigDecimal foodExpense,BigDecimal householdIncome,Boolean hasOtherAssets,Boolean hasOtherProperty,Boolean hasVehicle,Boolean receivesBolsaFamilia,Boolean receivesBpc,Boolean receivesRetirement){}
 public record DetailResponse(UUID id,StudentStatus status,String name,CatalogRef activity,LocalDate birthDate,String rg,String cpf,Boolean cadunico,String nis,String nationalHealthCard,String address,String neighborhood,String referencePoint,String city,String zipCode,LocalDate startDate,String guardianPhone,String guardianEmail,String studentPhone,String studentEmail,ParentsRelationshipStatus parentsRelationshipStatus,List<RelativeResponse> relatives,SocioeconomicResponse socioeconomic){} public record ListResponse(UUID id,StudentStatus status,String name,String cpf,String activity,LocalDate birthDate){}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) DetailResponse create(@Valid @RequestBody Request r){return detail(service.create(r));} @PutMapping("/{id}") DetailResponse update(@PathVariable UUID id,@Valid @RequestBody Request r){return detail(service.update(id,r));} @GetMapping("/{id}") DetailResponse get(@PathVariable UUID id){return detail(service.get(id));}
 @GetMapping public Page<ListResponse> list(@RequestParam(required=false) String name,@RequestParam(required=false) String cpf,@RequestParam(required=false) StudentStatus status,@PageableDefault(size=20,sort="name") Pageable pageable){return service.list(name,cpf,status,pageable).map(this::summary);} @PatchMapping("/{id}/status") DetailResponse status(@PathVariable UUID id,@Valid @RequestBody StatusRequest r){return detail(service.setStatus(id,r.status()));}
 private ListResponse summary(Student s){return new ListResponse(s.getId(),s.getStatus(),s.getName(),mask(s.getCpf()),s.getActivity().getName(),s.getBirthDate());} private DetailResponse detail(Student s){return new DetailResponse(s.getId(),s.getStatus(),s.getName(),ref(s.getActivity()),s.getBirthDate(),s.getRg(),s.getCpf(),s.getCadunico(),s.getNis(),s.getNationalHealthCard(),s.getAddress(),s.getNeighborhood(),s.getReferencePoint(),s.getCity(),s.getZipCode(),s.getStartDate(),s.getGuardianPhone(),s.getGuardianEmail(),s.getStudentPhone(),s.getStudentEmail(),s.getParentsRelationshipStatus(),s.getRelatives().stream().map(x->new RelativeResponse(x.getType(),x.getKinship(),x.getName(),x.getBirthDate(),ref(x.getOccupation()),x.getLiterate(),ref(x.getEducation()),x.getPhone(),x.getRg(),x.getCpf(),x.getVoterRegistration())).toList(),s.getSocioeconomicProfile()==null?null:profile(s.getSocioeconomicProfile()));}
 private SocioeconomicResponse profile(SocioeconomicProfile p){return new SocioeconomicResponse(ref(p.getHousingType()),ref(p.getAcquisitionType()),ref(p.getWallType()),ref(p.getFloorType()),p.getHasElectricity(),ref(p.getWaterSupply()),ref(p.getSewage()),ref(p.getGarbageCollection()),p.getWaterExpense(),p.getElectricityExpense(),p.getPhoneExpense(),p.getRentOrFinancingExpense(),p.getFoodExpense(),p.getHouseholdIncome(),p.getHasOtherAssets(),p.getHasOtherProperty(),p.getHasVehicle(),p.getReceivesBolsaFamilia(),p.getReceivesBpc(),p.getReceivesRetirement());} private CatalogRef ref(br.org.rosalina.social.catalog.CatalogItem x){return x==null?null:new CatalogRef(x.getId(),x.getName());} private String mask(String cpf){return cpf==null?null:"***.***."+cpf.substring(6,9)+"-**";}
}
